# Generated by Django 5.2.3 on 2025-07-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sliderproduct_delete_slideritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderProduct',
        ),
    ]
