# Generated by Django 5.2.3 on 2025-07-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_shopbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopBanner',
        ),
    ]
