# Generated by Django 5.2.3 on 2025-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_shopbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
            ],
        ),
    ]
