# Generated by Django 5.2.3 on 2025-07-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_shopbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbanner',
            name='image',
            field=models.ImageField(upload_to='shop_banner/'),
        ),
    ]
