# Generated by Django 5.2.3 on 2025-07-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_product_categories_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescriptionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mini_description', models.TextField(max_length=300)),
                ('rating', models.FloatField(default=0.0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('included_components', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=255)),
                ('descriptionboxes_title', models.CharField(max_length=255)),
                ('descriptionboxes_description', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(blank=True, to='myapp.category')),
                ('colors', models.ManyToManyField(blank=True, to='myapp.color')),
                ('ProductDescriptionBoxes', models.ManyToManyField(blank=True, related_name='products', to='myapp.productdescriptionbox')),
                ('images', models.ManyToManyField(blank=True, related_name='products', to='myapp.productimage')),
                ('sizes', models.ManyToManyField(blank=True, to='myapp.size')),
                ('tags', models.ManyToManyField(blank=True, to='myapp.tag')),
            ],
        ),
    ]
