# Generated by Django 5.2.3 on 2025-07-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_category_color_productdescriptionbox_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptionboxes_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descriptionboxes_title',
        ),
    ]
