# Generated by Django 5.2.4 on 2025-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_billingaddress_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Most_popular_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_now',
            field=models.BooleanField(default=False),
        ),
    ]
