# Generated by Django 5.2.4 on 2025-07-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_product_brand_alter_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mini_description',
            field=models.TextField(blank=True),
        ),
    ]
